// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBu5DyQIh5SUO8Pzh-Yx3WLlZCCvZULo',
    appId: '1:393458044744:web:76e08bc38e98631ac2ad7d',
    messagingSenderId: '393458044744',
    projectId: 'sos-vision',
    authDomain: 'sos-vision.firebaseapp.com',
    storageBucket: 'sos-vision.appspot.com',
    measurementId: 'G-YVYR4YHP1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJOzjIPIDwuTZIPZRuMnNbfHvchPkju4',
    appId: '1:393458044744:android:58ebb090dafeb160c2ad7d',
    messagingSenderId: '393458044744',
    projectId: 'sos-vision',
    storageBucket: 'sos-vision.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9i2riduMrt6p-_itkw2scz6x4z-2hM3U',
    appId: '1:393458044744:ios:bf52e03415d4f437c2ad7d',
    messagingSenderId: '393458044744',
    projectId: 'sos-vision',
    storageBucket: 'sos-vision.appspot.com',
    iosBundleId: 'com.example.sosVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9i2riduMrt6p-_itkw2scz6x4z-2hM3U',
    appId: '1:393458044744:ios:d994a345c04c3e78c2ad7d',
    messagingSenderId: '393458044744',
    projectId: 'sos-vision',
    storageBucket: 'sos-vision.appspot.com',
    iosBundleId: 'com.example.sosVision.RunnerTests',
  );
}
